sudo: required
dist: trusty
language: python
python:
  - "3.4"

before_install:
  - pip install -U pip

install:
  - pip install -Ue .[opencv]
  - sudo apt-get -qq update
  - sudo apt-get -qq install ghostscript

script:
  - python -m unittest -q cross2sheet.test.testdata
